---
title: "CMDA-4654  \n Project 2"
subtitle: "Project 2"
author: "Hipski, "
date: "Today's Date"
output:
  pdf_document:
    highlight: haddock
keep_tex: no
number_sections: no
html_document:
  df_print: paged
geometry: margin = 0.5in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
editor_options:
  chunk_output_type: console
documentclass: article
urlcolor: blue
---
  
<!-- The above is set to automatically compile to a .pdf file.   -->
<!-- It will only succeed if LaTeX is installed. -->


```{r setup, include=FALSE}
# This is the setup chunk
#  Here you can set global options for the entire document

library(knitr) # I recommend doing this here

# Although you can call functions from a library using the following notation
#  without loading the entire library.
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, # Required
                      fig.path = "./figures/",  # Store all figures here in relative path (make the folder first)
                      fig.align = "center",
                      fig.width = 7,
                      fig.height = 7,
                      message = FALSE, # Turn off load messages
                      warning = FALSE # Turn off warnings
                      )

```

\clearpage

```{r include=FALSE}
# You should not echo this chunk.
# include=FALSE does more than echo=FALSE, it actually does: echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'

# You should set your working directory at the very beginning of your R Markdown file
# setwd("~/Dropbox/teaching/FA2020/CMDA_4654/homework/homework1/")

# In linux ~/ is shorthand for /home/username/
# You should type things out properly for your system
# Mac: /Users/username/Documents/CMDA4654/Lectures/Lecture_03/.../
# Windows: C:/Users/username/Documents/etc/Lecture/Lecture_03/.../


```

<!-- ---------------------------------------------------------------------------------------------------- -->
<!-- ---------------- Homework Problems start below these lines ----------------------------------------- -->
<!-- ---------------------------------------------------------------------------------------------------- -->


# Problem 1

## Part a

Example Chunk Below

```{r}
myprobit = function(X, y, max_iter, tolerance){

  m = ncol(X)
  beta <- rep(0, m)
  
  for (i in 1:max_iter) {
    
    eta <- X %*% beta
    
    phat <- pnorm(eta)
    qhat <- dnorm(eta)
    
    ratio <- qhat / (phat * (1 - phat))
    score <- (y - phat) * ratio
    g <- t(X) %*% score
    
    w <- (qhat^2) / (phat * (1 - phat))
    H <- -t(X) %*% (X * as.vector(w))
    
    copy_beta = beta
    beta <- beta - solve(H, g)
    
    cat("Iteration", i, ":\n")
    j=1
    for (b in beta){
      cat("Beta", j, " = ", beta[j], "\n")
      j=j+1
    }
    if ((sum(beta - copy_beta)^2) < tolerance) {
      break
    }
  }
}
```


```{r}
summary(mtcars)
X <- model.matrix(am ~ mpg, data = mtcars)
y <- mtcars$am
myprobit(X,y,32, 0.00009)

```



